=== buildingSMART/IFC4.3.x-output-2/IFC/RELEASE/IFC2x/FINAL/HTML/psd/PSD_R2x.dtd
<?xml version ="1.0" encoding='UTF-8' ?>

<!--
# Property Set Definition markup language (PSD)

# Author: adachi@ai.isl.secom.co.jp (Yoshinobu Adachi)
# Version: 0.91
# Organization: International Alliance for Interoperability MSG
# Date: 1999/06/28 0.1
        1999/12/15 0.2
        2000/02/07 0.3
        2000/03/22 0.4 add R2.x enumeration
        2000/03/24 0.5 bug fix
        2000/03/30 0.6 TypePropertyList -> TypeComplexProperty
        2000/03/31 0.7 add Schema element
        2000/04/12 0.8 add ThermodynamicTemperatureUnit to UnitType
        2000/10/01 0.9
        2000/10/17 0.91 removed ValueDef from PropertyDef child level
-->
<!-- ************************************************ -->
<!-- PropertySet body definition                      -->
<!-- ************************************************ -->
<!ELEMENT PropertySetDef  (IfcVersion , Name ,  (Definition? ) , Typed , TypedClass , TypeName , PropertyDefs )>

<!ELEMENT IfcVersion EMPTY>

<!-- ************************************************ -->
<!-- Other attribute list definition                  -->
<!-- ************************************************ -->
<!ATTLIST IfcVersion version NMTOKEN  "2.0">

<!ATTLIST IfcVersion schema  CDATA    #IMPLIED>

<!ELEMENT Name  (#PCDATA )>

<!ELEMENT Definition  (#PCDATA )>
<!ATTLIST Definition  lang CDATA  #IMPLIED >
<!ELEMENT Typed  (#PCDATA )>

<!ELEMENT TypedClass  (#PCDATA )>

<!ELEMENT TypeName  (#PCDATA )>

<!ELEMENT PropertyDefs  (PropertyDef* )>

<!ELEMENT PropertyDef  (Name | PropertyType | ValueDef | Definition )*>
<!ATTLIST PropertyDef  name NMTOKEN  #IMPLIED
                       id   NMTOKEN  #REQUIRED >
<!ELEMENT PropertyType  (TypePropertySingleValue | TypePropertyEnumeratedValue | TypePropertyBoundedValue | TypePropertyTableValue | TypePropertyReferenceValue | TypeComplexProperty )>

<!-- ************************************************ -->
<!-- Property body definition                         -->
<!-- ************************************************ -->
<!ELEMENT TypePropertySingleValue  (DataType , UnitType? )>

<!ELEMENT TypePropertyEnumeratedValue  (EnumList )>

<!ELEMENT TypeComplexProperty  (PropertyType )>
<!ATTLIST TypeComplexProperty  ubound CDATA    #IMPLIED
                               name   NMTOKEN  #IMPLIED
                               lbound CDATA    #IMPLIED >
<!ELEMENT TypePropertyReferenceValue EMPTY>
<!ATTLIST TypePropertyReferenceValue  name        NMTOKEN  #IMPLIED
                                      reftype     NMTOKEN  #REQUIRED
                                      guid        NMTOKEN  #IMPLIED
                                      URL         CDATA    #IMPLIED
                                      libraryname CDATA    #IMPLIED
                                      sectionref  CDATA    #IMPLIED >
<!ELEMENT TypePropertyTableValue  (DefiningUnit? , DefinedUnit? )>
<!ATTLIST TypePropertyTableValue  expression CDATA  #IMPLIED >
<!-- ************************************************ -->
<!-- Data type and Unit type definition               -->
<!-- ************************************************ -->
<!ELEMENT DataType EMPTY>
<!ATTLIST DataType  type  (IfcAmountOfSubstanceMeasure | 
                           IfcAngularVelocityMeasure | 
                           IfcAreaMeasure | 
                           IfcBoolean | 
                           IfcCompoundPlaneAngleMeasure | 
                           IfcContextDependentMeasure | 
                           IfcCountMeasure | 
                           IfcDescriptiveMeasure | 
                           IfcDynamicViscosityMeasure | 
                           IfcElectricCurrentMeasure | 
                           IfcElectricVoltageMeasure | 
                           IfcEnergyMeasure | 
                           IfcHeatfluxDensityMeasure | 
                           IfcIdentifier | 
                           IfcInteger | 
                           IfcIntegerCountMeasure | 
                           IfcIntegerCountRateMeasure | 
                           IfcKinematicViscosityMeasure | 
                           IfcLengthMeasure | 
                           IfcLinearVelocityMeasure | 
                           IfcLuminousIntensityMeasure | 
                           IfcMassDensityMeasure | 
                           IfcMassFlowRateMeasure | 
                           IfcMassMeasure | 
                           IfcMonetaryMeasure | 
                           IfcNumericMeasure | 
                           IfcParameterValue | 
                           IfcPercentMeasure | 
                           IfcPlaneAngleMeasure | 
                           IfcPositiveLengthMeasure | 
                           IfcPositivePlaneAngleMeasure | 
                           IfcPositiveRatioMeasure | 
                           IfcPowerMeasure | 
                           IfcPressureMeasure | 
                           IfcRatioMeasure | 
                           IfcReal | 
                           IfcRotationalFrequencyMeasure | 
                           IfcSolidAngleMeasure | 
                           IfcString | 
                           IfcThermalAdmittanceMeasure | 
                           IfcThermalResistanceMeasure | 
                           IfcThermalTransmittanceMeasure | 
                           IfcThermodynamicTemperatureMeasure | 
                           IfcTimeDurationMeasure | 
                           IfcTimeMeasure | 
                           IfcTimeStamp | 
                           IfcVolumeMeasure | 
                           IfcVolumetricFlowRateMeasure )  'IfcString' >
<!ELEMENT UnitType EMPTY>
<!ATTLIST UnitType  type  (VolumetricFlowrateUnit | 
                           MassFlowrateUnit | 
                           PressureUnit | 
                           EnergyUnit | 
                           PowerUnit | 
                           AngularVelocityUnit | 
                           LinearVelocityUnit | 
                           RotationalFrequencyUnit | 
                           HeatfluxDensityUnit | 
                           MassDensityUnit | 
                           ThermalResistanceUnit | 
                           ThermalTransmittanceUnit | 
                           ThermodynamicTemperatureUnit | 
                           InfiltatationUnit | 
                           VoltageUnit | 
                           DynamicViscosityUnit | 
                           KinematicViscosityUnit | 
                           UserDefined | 
                           Unspecified )  'Unspecified' >
<!ELEMENT EnumList  ( (EnumItem )* , DataType? , UnitType? )>
<!ATTLIST EnumList  name CDATA  #REQUIRED >
<!ELEMENT EnumItem  (#PCDATA )>

<!-- ************************************************ -->
<!-- Value definition                                 -->
<!-- ************************************************ -->
<!ELEMENT ValueDef  (MinValue | MaxValue | DefaultValue )*>

<!ELEMENT MinValue EMPTY>
<!ATTLIST MinValue  value CDATA  #IMPLIED >
<!ELEMENT MaxValue EMPTY>
<!ATTLIST MaxValue  value CDATA  #IMPLIED >
<!ELEMENT DefaultValue EMPTY>
<!ATTLIST DefaultValue  value CDATA  #IMPLIED >
<!ELEMENT TypePropertyBoundedValue  (ValueRangeDef , DataType? , UnitType? )>

<!ELEMENT DefiningUnit  (UnitType )>

<!ELEMENT DefinedUnit  (UnitType )>

<!-- ************************************************ -->
<!-- ValueRange definition                            -->
<!-- ************************************************ -->
<!ELEMENT ValueRangeDef  (LowerBoundValue | UpperBoundValue )>

<!ELEMENT LowerBoundValue EMPTY>
<!ATTLIST LowerBoundValue  value CDATA  #IMPLIED >
<!ELEMENT UpperBoundValue EMPTY>
<!ATTLIST UpperBoundValue  value CDATA  #IMPLIED >

=== buildingSMART/IFC4.3.x-output-2/IFC/RELEASE/IFC2x/ADD1/HTML/psd/Pset_OpeningElementCommon.xml
<?xml version="1.0"?>
<!DOCTYPE PropertySetDef SYSTEM "PSD_R2x.dtd">
<?xml-stylesheet type="text/xsl" href="PSD_R2x.xsl"?>
<PropertySetDef>
  <IfcVersion version="2.x" schema="IfcProductExtension"/>
  <Name>Pset_OpeningElementCommon</Name>
  <Definition>Definition from IAI: Properties common to the definition of all generic opening types 'Recess' of IfcOpeningElement.</Definition>
  <Typed>True</Typed>
  <TypedClass>IfcOpeningElement</TypedClass>
  <TypeName></TypeName>
  <PropertyDefs>
    <PropertyDef id="34">
      <Name>Description</Name>
      <PropertyType>
        <TypePropertySingleValue>
          <DataType type="IfcString"/>
        </TypePropertySingleValue>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="empty string"/>
      </ValueDef>
      <Definition>
Description of this opening.
      </Definition>
    </PropertyDef>

    <PropertyDef id="863">
      <Name>ParallelJambs</Name>
      <PropertyType>
        <TypePropertySingleValue>
          <DataType type="IfcBoolean"/>
        </TypePropertySingleValue>
      </PropertyType>
      <ValueDef>
        <MinValue value="False"/>
        <MaxValue value="True"/>
        <DefaultValue value="True"/>
      </ValueDef>
      <Definition>
Indicated, whether the jambs of an opening in a curved building element are intended to be parallel (TRUE) or are radial (FALSE). Radial means, that the extension of the jambs are rays through the axis of the revolution
forming the curved building element.
      </Definition>
    </PropertyDef>

  </PropertyDefs>
</PropertySetDef>

=== buildingSMART/IFC4.3.x-output-2/IFC/RELEASE/IFC2x2/ADD1/HTML/psd/Pset_PipeFitting.xml
<?xml version="1.0"?>
<!DOCTYPE PropertySetDef SYSTEM "PSD_R2x.dtd">
<?xml-stylesheet type="text/xsl" href="PSD_R2x.xsl"?>
<PropertySetDef>
  <IfcVersion version="2.x" schema="IfcSharedBldgServiceElements"/>
  <Name>Pset_PipeFitting</Name>
  <Definition>Definition from IAI: This property set is used to define the characteristics of a pipe fitting. Related property sets include Pset_PipeDesignCriteria.

HISTORY: New property set in IFC Release 2.0.

ISSUES: No issues to date.</Definition>
  <Typed>True</Typed>
  <TypedClass>IfcFlowFitting</TypedClass>
  <TypeName>PipeFitting</TypeName>
  <PropertyDefs>
    <PropertyDef id="573">
      <Name>FittingSubTypeEnum</Name>
      <PropertyType>
        <TypePropertyEnumeratedValue>
          <EnumList name="Pset_PipeFittingSubtypeEnum">
            <EnumItem>45DegreeElbow</EnumItem>
            <EnumItem>90DegreeElbow</EnumItem>
            <EnumItem>Cap</EnumItem>
            <EnumItem>Cock</EnumItem>
            <EnumItem>Crossover</EnumItem>
            <EnumItem>DoubleBranchElbow</EnumItem>
            <EnumItem>Flange</EnumItem>
            <EnumItem>Lateral</EnumItem>
            <EnumItem>PipeJoint</EnumItem>
            <EnumItem>Plug</EnumItem>
            <EnumItem>Reducer</EnumItem>
            <EnumItem>ReducingElbow</EnumItem>
            <EnumItem>Sleeve</EnumItem>
            <EnumItem>StreetElbow</EnumItem>
            <EnumItem>Tee</EnumItem>
            <EnumItem>Union</EnumItem>
            <EnumItem>Other</EnumItem>
            <EnumItem>NotKnown</EnumItem>
            <EnumItem>Unset</EnumItem>
          </EnumList>
        </TypePropertyEnumeratedValue>
      </PropertyType>
      <ValueDef>
        <MinValue value=""/>
        <MaxValue value=""/>
        <DefaultValue value=""/>
      </ValueDef>
      <Definition>
This enumeration identifies the fitting subtype.
      </Definition>
    </PropertyDef>

  </PropertyDefs>
</PropertySetDef>

=== buildingSMART/IFC4.3.x-output-2/IFC/RELEASE/IFC2x/ADD1/HTML/psd/Pset_BinaryOutput.xml
<?xml version="1.0"?>
<!DOCTYPE PropertySetDef SYSTEM "PSD_R2x.dtd">
<?xml-stylesheet type="text/xsl" href="PSD_R2x.xsl"?>
<PropertySetDef>
  <IfcVersion version="2.x" schema="IfcHvacDomain"/>
  <Name>Pset_BinaryOutput</Name>
  <Definition>Definition from IAI: This property set is used to define the characteristics of a binary output.

HISTORY: New property set in IFC Release 2.0.

ISSUES: No issues to date.</Definition>
  <Typed>False</Typed>
  <TypedClass></TypedClass>
  <TypeName></TypeName>
  <PropertyDefs>
    <PropertyDef id="110">
      <Name>PolarityEnum</Name>
      <PropertyType>
        <TypePropertyEnumeratedValue>
          <EnumList name="Pset_PolarityEnum">
            <EnumItem>Normal</EnumItem>
            <EnumItem>Reverse</EnumItem>
            <EnumItem>Other</EnumItem>
            <EnumItem>NotKnown</EnumItem>
            <EnumItem>Unset</EnumItem>
          </EnumList>
        </TypePropertyEnumeratedValue>
      </PropertyType>
      <ValueDef>
        <MinValue value=""/>
        <MaxValue value=""/>
        <DefaultValue value=""/>
      </ValueDef>
      <Definition>
Enumeration defining the polarity
      </Definition>
    </PropertyDef>

    <PropertyDef id="111">
      <Name>InactiveText</Name>
      <PropertyType>
        <TypePropertySingleValue>
          <DataType type="IfcString"/>
        </TypePropertySingleValue>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="empty string"/>
      </ValueDef>
      <Definition>
String value to be displayed in an inactive, off, or idle state
      </Definition>
    </PropertyDef>

    <PropertyDef id="112">
      <Name>ActiveText</Name>
      <PropertyType>
        <TypePropertySingleValue>
          <DataType type="IfcString"/>
        </TypePropertySingleValue>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="empty string"/>
      </ValueDef>
      <Definition>
String value to be displayed in an active, on, or running state
      </Definition>
    </PropertyDef>

    <PropertyDef id="119">
      <Name>MinimumOffTime</Name>
      <PropertyType>
        <TypePropertyReferenceValue reftype="IfcLocalTime"/>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="NIL"/>
      </ValueDef>
      <Definition>
Minimum Off Time
      </Definition>
    </PropertyDef>

    <PropertyDef id="120">
      <Name>MinimumOnTime</Name>
      <PropertyType>
        <TypePropertyReferenceValue reftype="IfcLocalTime"/>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="NIL"/>
      </ValueDef>
      <Definition>
Minimum On Time
      </Definition>
    </PropertyDef>

    <PropertyDef id="121">
      <Name>FeedbackValueEnum</Name>
      <PropertyType>
        <TypePropertyEnumeratedValue>
          <EnumList name="Pset_FeedbackValueEnum">
            <EnumItem>Inactive</EnumItem>
            <EnumItem>Active</EnumItem>
            <EnumItem>Other</EnumItem>
            <EnumItem>NotKnown</EnumItem>
            <EnumItem>Unset</EnumItem>
          </EnumList>
        </TypePropertyEnumeratedValue>
      </PropertyType>
      <ValueDef>
        <MinValue value=""/>
        <MaxValue value=""/>
        <DefaultValue value=""/>
      </ValueDef>
      <Definition>
Enumeration defining the feedback value from the control system element
      </Definition>
    </PropertyDef>

    <PropertyDef id="77">
      <Name>EventEnableEnum</Name>
      <PropertyType>
        <TypePropertyEnumeratedValue>
          <EnumList name="Pset_EventEnableEnum">
            <EnumItem>To-OffNormal</EnumItem>
            <EnumItem>To-Fault</EnumItem>
            <EnumItem>To-Normal</EnumItem>
            <EnumItem>Other</EnumItem>
            <EnumItem>NotKnown</EnumItem>
            <EnumItem>Unset</EnumItem>
          </EnumList>
        </TypePropertyEnumeratedValue>
      </PropertyType>
      <ValueDef>
        <MinValue value=""/>
        <MaxValue value=""/>
        <DefaultValue value=""/>
      </ValueDef>
      <Definition>
Enumeration that defines the type of event enabling
      </Definition>
    </PropertyDef>

    <PropertyDef id="115">
      <Name>AckedTransitionsEnum</Name>
      <PropertyType>
        <TypePropertyEnumeratedValue>
          <EnumList name="Pset_AckedTransitionsEnum">
            <EnumItem>To-OffNormal</EnumItem>
            <EnumItem>To-Fault</EnumItem>
            <EnumItem>To-Normal</EnumItem>
            <EnumItem>Other</EnumItem>
            <EnumItem>NotKnown</EnumItem>
            <EnumItem>Unset</EnumItem>
          </EnumList>
        </TypePropertyEnumeratedValue>
      </PropertyType>
      <ValueDef>
        <MinValue value=""/>
        <MaxValue value=""/>
        <DefaultValue value=""/>
      </ValueDef>
      <Definition>
Enumeration that defines the type of transition acknowledgement
      </Definition>
    </PropertyDef>

  </PropertyDefs>
</PropertySetDef>

=== buildingSMART/IFC4.3.x-output-2/IFC/RELEASE/IFC2x/FINAL/HTML/psd/Pset_DuctSystemDesignCriteria.xml
<?xml version="1.0"?>
<!DOCTYPE PropertySetDef SYSTEM "PSD_R2x.dtd">
<?xml-stylesheet type="text/xsl" href="PSD_R2x.xsl"?>
<PropertySetDef>
  <IfcVersion version="2.x" schema="IfcProductExtension"/>
  <Name>Pset_DuctSystemDesignCriteria</Name>
  <Definition>Definition from IAI: This property set is used to define the general characteristics of the duct system and is typically attached to an instance of an IfcSystem.

HISTORY: New property set in IFC Release 2.0.

ISSUES: No issues to date.</Definition>
  <Typed>False</Typed>
  <TypedClass></TypedClass>
  <TypeName></TypeName>
  <PropertyDefs>
    <PropertyDef id="283">
      <Name>DuctSystemTypeEnum</Name>
      <PropertyType>
        <TypePropertyEnumeratedValue>
          <EnumList name="Pset_DuctSystemTypeEnum">
            <EnumItem>VariableAirVolume</EnumItem>
            <EnumItem>ConstantVolume</EnumItem>
            <EnumItem>DoubleDuct</EnumItem>
            <EnumItem>Other</EnumItem>
            <EnumItem>NotKnown</EnumItem>
            <EnumItem>Unset</EnumItem>
          </EnumList>
        </TypePropertyEnumeratedValue>
      </PropertyType>
      <ValueDef>
        <MinValue value=""/>
        <MaxValue value=""/>
        <DefaultValue value=""/>
      </ValueDef>
      <Definition>
Enumeration that identifies the type of system
      </Definition>
    </PropertyDef>

    <PropertyDef id="284">
      <Name>SystemDescription</Name>
      <PropertyType>
        <TypePropertySingleValue>
          <DataType type="IfcString"/>
        </TypePropertySingleValue>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="empty string"/>
      </ValueDef>
      <Definition>
System description
      </Definition>
    </PropertyDef>

    <PropertyDef id="285">
      <Name>SystemLocation</Name>
      <PropertyType>
        <TypePropertySingleValue>
          <DataType type="IfcString"/>
        </TypePropertySingleValue>
      </PropertyType>
      <ValueDef>
        <MinValue value="see type"/>
        <MaxValue value="see type"/>
        <DefaultValue value="empty string"/>
      </ValueDef>
      <Definition>
Physical description of the part of the building the system serves
      </Definition>
    </PropertyDef>

  </PropertyDefs>
</PropertySetDef>
